POST http://localhost:8080/owners/create
Accept: application/json
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com"
}

###



POST http://localhost:8080/addresses/create
Accept: application/json
Content-Type: application/json

{
  "street": "Random",
  "number": 1,
  "postalCode": "2000",
  "city": "Antwerpen",
  "country": "Belgium"
}
###

POST http://localhost:8080/restaurants/create
Accept: application/json
Content-Type: application/json

{
  "nameOfRestaurant": "Good Food",
  "cuisine": "ITALIAN",
  "openingStatus": "OPEN",
  "defaultPreparationTime": 20,
  "contactEmail": "contact@goodfood.com",
  "picture": "goodfood.png",
  "addressId": "583cc59d-1641-4fd7-98c1-6ec474a22156",
  "ownerId": "9f266649-1158-4c4a-8ea9-3692df185818"
}

###
POST http://localhost:8080/menus/create
Accept: application/json
Content-Type: application/json

{

}

###
POST http://localhost:8080/dishes/create
Accept: application/json
Content-Type: application/json

{
  "quantity": 23,
  "status": "PUBLISHED",
  "menu": {
    "menuId": {
      "uuid": "7ca09c79-b668-4003-9ea0-90c52bfe3bb1"
    }
  }

}